name: Nodejs CI

on: [push]

jobs:
  build:
    name: Test Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install build, and test
        run: |
          npm install
          npm run build --if-present
      - name: Code Linting
        run: npm run lint
      - name: Run prettier
        run: |-
          npx prettier --check 'public/*[!.min].js'
